server:
  port: 8999
  
eureka:  instance:    hostname: localhost
    
spring:  application:    name: api-gateway
  cloud:    gateway:      routes:      - id:   
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id : contact-service
        uri: lb://contact-service
        predicates:        - Path=/contact/**
        